Api 2444 consolidate alb rules
department-of-veterans-affairs/health-apis-deployer pull request #417
Opened 2020-09-15 20:55 UTC by eclendenning-va

Is this a new product?
No

Has this been deployed successfully from a branch?
Yes

Are load balancer rules being removed or renamed?
Yes

Are Kubernetes namespaces being removed or renamed?
No

Has DevOps been consulted on resource limits?
N/A

2020-09-15 21:00 UTC, jhulbert-va requested changes

2020-09-15 21:00 UTC, jhulbert-va commented on products/data-query.conf
> +DU_LOAD_BALANCER_RULES[70]="/fhir/v0/argonaut/data-query/*"
These should not have moved up

2020-09-15 21:18 UTC, jhulbert-va approved these changes

2020-09-16 15:30 UTC, mramirez-va approved these changes

2020-09-16 15:42 UTC, merged